# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
#name: dave lawrence
title: principal software engineer
email: info@davidlawrence.eu
website: www.davidlawrence.eu
# Social links
# twitter_username: facespics
github_username:  lawred2
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: davidjmlawrence
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/4548982.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Dave; a principal full stack engineer based in Dublin - primarily with <mark>.net/.net core</mark> but with a healthy spread of javascript, html, sql, and nodejs... Currently the team lead of a dedicated software automation group focused on delivering test and process automation solutions for a fintech organisation

  I would consider myself most skilled in: <mark>C#</mark> with <mark>asp.net</mark> and lately I've also been working a lot with: <mark>reactjs</mark> and <mark>cloudflare workers</mark> 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in platform and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
