# Site
repository: sproogen/resume-theme
favicon: images/favicon.png

# Personal info
name: david lawrence
title: solutions architect
email: info@davidlawrence.eu
website: www.davidlawrence.eu
# Social links
# twitter_username: facespics
github_username:  lawred2
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: davidjmlawrence
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/logo.png
about_content: | # this will include new lines to allow paragraphs
  A principal full stack engineer based in Dublin - primarily with <mark>.net/.net core</mark> but with a healthy spread of javascript, html, sql, and nodejs... Currently solutions architect focused on designing and delivering technical solutions to complex business and technical problems

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in platform and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
